version: '3'

services:
  api:
    build: ./server
    container_name: code-analyzer-api
    restart: unless-stopped
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/code-analyzer
      - JWT_SECRET=your_jwt_secret_key_here
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GITHUB_TOKEN=your_github_personal_access_token
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  client:
    build: ./client
    container_name: code-analyzer-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
